spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST_NAME}/${DB_STORAGE_NAME}?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_AUTH_ID}
    password: ${DB_AUTH_PASSWORD}
  redis:
    host: localhost
    port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 441372306958-ape9d8nhhj8gp1sdh7emn8kvhfv98kb7.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

filePath: /images/