spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST_NAME}/${DB_STORAGE_NAME}?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_AUTH_ID}
    password: ${DB_AUTH_PASSWORD}
  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}
  security:
    oauth2:
      client:
        preEstablishedRedirectUri: https://codetech.nworld.dev/login/oauth2/code/google
        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id
        registration:
          google:
            clientId: ${OAUTH2_CLIENT_ID}
            clientSecret: ${OAUTH2_SECRET}
            scope:
              - email
              - profile
  mail:
    host: smtp.naver.com
    port: 465
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 300
  refresh-token-expiration-minutes: 420

filePath: /images/
